# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@astrojs/compiler-2.12.2" = {
      name = "_at_astrojs_slash_compiler";
      packageName = "@astrojs/compiler";
      version = "2.12.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@astrojs/compiler/-/compiler-2.12.2.tgz";
        sha512 = "w2zfvhjNCkNMmMMOn5b0J8+OmUaBL1o40ipMvqcG6NRpdC+lKxmTi48DT8Xw0SzJ3AfmeFLB45zXZXtmbsjcgw==";
      };
    };
    "@avh4/elm-format-darwin-arm64-0.8.7-2" = {
      name = "_at_avh4_slash_elm-format-darwin-arm64";
      packageName = "@avh4/elm-format-darwin-arm64";
      version = "0.8.7-2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@avh4/elm-format-darwin-arm64/-/elm-format-darwin-arm64-0.8.7-2.tgz";
        sha512 = "F5JD44mJ3KX960J5GkXMfh1/dtkXuPcQpX2EToHQKjLTZUfnhZ++ytQQt0gAvrJ0bzoOvhNzjNjUHDA1ruTVbg==";
      };
    };
    "@avh4/elm-format-darwin-x64-0.8.7-2" = {
      name = "_at_avh4_slash_elm-format-darwin-x64";
      packageName = "@avh4/elm-format-darwin-x64";
      version = "0.8.7-2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@avh4/elm-format-darwin-x64/-/elm-format-darwin-x64-0.8.7-2.tgz";
        sha512 = "4pfF1cl0KyTion+7Mg4XKM3yi4Yc7vP76Kt/DotLVGJOSag4ISGic1og2mt8RZZ7XArybBmHNyYkiUbe/cEiCw==";
      };
    };
    "@avh4/elm-format-linux-arm64-0.8.7-2" = {
      name = "_at_avh4_slash_elm-format-linux-arm64";
      packageName = "@avh4/elm-format-linux-arm64";
      version = "0.8.7-2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@avh4/elm-format-linux-arm64/-/elm-format-linux-arm64-0.8.7-2.tgz";
        sha512 = "WkVmuce2zU6s9dupHhqPc886Vaqpea8dZlxv2fpZ4wSzPUbiiKHoHZzoVndMIMTUL0TZukP3Ps0n/lWO5R5+FA==";
      };
    };
    "@avh4/elm-format-linux-x64-0.8.7-2" = {
      name = "_at_avh4_slash_elm-format-linux-x64";
      packageName = "@avh4/elm-format-linux-x64";
      version = "0.8.7-2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@avh4/elm-format-linux-x64/-/elm-format-linux-x64-0.8.7-2.tgz";
        sha512 = "kmncfJrTBjVT94JtQvMf4M5Pn2Yl0sZt3wo7AzgFiDnB/CiZ+KjJyXuWM64NeGiv4MQqzPq65tsFXUH1CIJeiQ==";
      };
    };
    "@avh4/elm-format-win32-x64-0.8.7-2" = {
      name = "_at_avh4_slash_elm-format-win32-x64";
      packageName = "@avh4/elm-format-win32-x64";
      version = "0.8.7-2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@avh4/elm-format-win32-x64/-/elm-format-win32-x64-0.8.7-2.tgz";
        sha512 = "sBdMBGq/8mD8Y5C+fIr5vlb3N50yB7S1MfgeAq2QEbvkr/sKrCZI540i43lZDH9gWsfA1w2W8wCe0penFYzsGw==";
      };
    };
    "@bytecodealliance/preview2-shim-0.17.2" = {
      name = "_at_bytecodealliance_slash_preview2-shim";
      packageName = "@bytecodealliance/preview2-shim";
      version = "0.17.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@bytecodealliance/preview2-shim/-/preview2-shim-0.17.2.tgz";
        sha512 = "mNm/lblgES8UkVle8rGImXOz4TtL3eU3inHay/7TVchkKrb/lgcVvTK0+VAw8p5zQ0rgQsXm1j5dOlAAd+MeoA==";
      };
    };
    "@chevrotain/cst-dts-gen-10.5.0" = {
      name = "_at_chevrotain_slash_cst-dts-gen";
      packageName = "@chevrotain/cst-dts-gen";
      version = "10.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@chevrotain/cst-dts-gen/-/cst-dts-gen-10.5.0.tgz";
        sha512 = "lhmC/FyqQ2o7pGK4Om+hzuDrm9rhFYIJ/AXoQBeongmn870Xeb0L6oGEiuR8nohFNL5sMaQEJWCxr1oIVIVXrw==";
      };
    };
    "@chevrotain/gast-10.5.0" = {
      name = "_at_chevrotain_slash_gast";
      packageName = "@chevrotain/gast";
      version = "10.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@chevrotain/gast/-/gast-10.5.0.tgz";
        sha512 = "pXdMJ9XeDAbgOWKuD1Fldz4ieCs6+nLNmyVhe2gZVqoO7v8HXuHYs5OV2EzUtbuai37TlOAQHrTDvxMnvMJz3A==";
      };
    };
    "@chevrotain/types-10.5.0" = {
      name = "_at_chevrotain_slash_types";
      packageName = "@chevrotain/types";
      version = "10.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@chevrotain/types/-/types-10.5.0.tgz";
        sha512 = "f1MAia0x/pAVPWH/T73BJVyO2XU5tI4/iE7cnxb7tqdNTNhQI3Uq3XkqcoteTmD4t1aM0LbHCJOhgIDn07kl2A==";
      };
    };
    "@chevrotain/utils-10.5.0" = {
      name = "_at_chevrotain_slash_utils";
      packageName = "@chevrotain/utils";
      version = "10.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@chevrotain/utils/-/utils-10.5.0.tgz";
        sha512 = "hBzuU5+JjB2cqNZyszkDHZgOSrUUT8V3dhgRl8Q9Gp6dAj/H5+KILGjbhDpc3Iy9qmqlm/akuOI2ut9VUtzJxQ==";
      };
    };
    "@cucumber/gherkin-27.0.0" = {
      name = "_at_cucumber_slash_gherkin";
      packageName = "@cucumber/gherkin";
      version = "27.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cucumber/gherkin/-/gherkin-27.0.0.tgz";
        sha512 = "j5rCsjqzRiC3iVTier3sa0kzyNbkcAmF7xr7jKnyO7qDeK3Z8Ye1P3KSVpeQRMY+KCDJ3WbTDdyxH0FwfA/fIw==";
      };
    };
    "@cucumber/messages-22.0.0" = {
      name = "_at_cucumber_slash_messages";
      packageName = "@cucumber/messages";
      version = "22.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cucumber/messages/-/messages-22.0.0.tgz";
        sha512 = "EuaUtYte9ilkxcKmfqGF9pJsHRUU0jwie5ukuZ/1NPTuHS1LxHPsGEODK17RPRbZHOFhqybNzG2rHAwThxEymg==";
      };
    };
    "@cucumber/messages-23.0.0" = {
      name = "_at_cucumber_slash_messages";
      packageName = "@cucumber/messages";
      version = "23.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@cucumber/messages/-/messages-23.0.0.tgz";
        sha512 = "2ZWKNnikNMBnle3P3cgy+fgzhABrY4oBbiWp9wcI8ANdT4LlYRN6jQ6j/9CQGTDGRfkyRtr/5VkYq7q24XCsuA==";
      };
    };
    "@hapi/hoek-9.3.0" = {
      name = "_at_hapi_slash_hoek";
      packageName = "@hapi/hoek";
      version = "9.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/hoek/-/hoek-9.3.0.tgz";
        sha512 = "/c6rf4UJlmHlC9b5BaNvzAcFv7HZ2QHaV0D4/HNlBdvFnvQq8RI4kYdhyPCl7Xj+oWvTWQ8ujhqS53LIgAe6KQ==";
      };
    };
    "@hapi/topo-5.1.0" = {
      name = "_at_hapi_slash_topo";
      packageName = "@hapi/topo";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@hapi/topo/-/topo-5.1.0.tgz";
        sha512 = "foQZKJig7Ob0BMAYBfcJk8d77QtOe7Wo4ox7ff1lQYoNNAb6jwcY1ncdoy2e9wQZzvNy7ODZCYJkK8kzmcAnAg==";
      };
    };
    "@jridgewell/gen-mapping-0.3.13" = {
      name = "_at_jridgewell_slash_gen-mapping";
      packageName = "@jridgewell/gen-mapping";
      version = "0.3.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/gen-mapping/-/gen-mapping-0.3.13.tgz";
        sha512 = "2kkt/7niJ6MgEPxF0bYdQ6etZaA+fQvDcLKckhy1yIQOzaoKjBBjSj63/aLVjYE3qhRt5dvM+uUyfCg6UKCBbA==";
      };
    };
    "@jridgewell/remapping-2.3.5" = {
      name = "_at_jridgewell_slash_remapping";
      packageName = "@jridgewell/remapping";
      version = "2.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/remapping/-/remapping-2.3.5.tgz";
        sha512 = "LI9u/+laYG4Ds1TDKSJW2YPrIlcVYOwi2fUC6xB43lueCjgxV4lffOCZCtYFiH6TNOX+tQKXx97T4IKHbhyHEQ==";
      };
    };
    "@jridgewell/resolve-uri-3.1.2" = {
      name = "_at_jridgewell_slash_resolve-uri";
      packageName = "@jridgewell/resolve-uri";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/resolve-uri/-/resolve-uri-3.1.2.tgz";
        sha512 = "bRISgCIjP20/tbWSPWMEi54QVPRZExkuD9lJL+UIxUKtwVJA8wW1Trb1jMs1RFXo1CBTNZ/5hpC9QvmKWdopKw==";
      };
    };
    "@jridgewell/sourcemap-codec-1.5.5" = {
      name = "_at_jridgewell_slash_sourcemap-codec";
      packageName = "@jridgewell/sourcemap-codec";
      version = "1.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.5.5.tgz";
        sha512 = "cYQ9310grqxueWbl+WuIUIaiUaDcj7WOq5fVhEljNVgRfOUhY9fy2zTvfoqWsnebh8Sl70VScFbICvJnLKB0Og==";
      };
    };
    "@jridgewell/trace-mapping-0.3.30" = {
      name = "_at_jridgewell_slash_trace-mapping";
      packageName = "@jridgewell/trace-mapping";
      version = "0.3.30";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/trace-mapping/-/trace-mapping-0.3.30.tgz";
        sha512 = "GQ7Nw5G2lTu/BtHTKfXhKHok2WGetd4XYcVKGx00SjAk8GMwgJM3zr6zORiPGuOE+/vkc90KtTosSSvaCjKb2Q==";
      };
    };
    "@korzio/djv-draft-04-2.0.1" = {
      name = "_at_korzio_slash_djv-draft-04";
      packageName = "@korzio/djv-draft-04";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@korzio/djv-draft-04/-/djv-draft-04-2.0.1.tgz";
        sha512 = "MeTVcNsfCIYxK6T7jW1sroC7dBAb4IfLmQe6RoCqlxHN5NFkzNpgdnBPR+/0D2wJDUJHM9s9NQv+ouhxKjvUjg==";
      };
    };
    "@netflix/nerror-1.1.3" = {
      name = "_at_netflix_slash_nerror";
      packageName = "@netflix/nerror";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@netflix/nerror/-/nerror-1.1.3.tgz";
        sha512 = "b+MGNyP9/LXkapreJzNUzcvuzZslj/RGgdVVJ16P2wSlYatfLycPObImqVJSmNAdyeShvNeM/pl3sVZsObFueg==";
      };
    };
    "@nomicfoundation/slang-1.2.0" = {
      name = "_at_nomicfoundation_slash_slang";
      packageName = "@nomicfoundation/slang";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nomicfoundation/slang/-/slang-1.2.0.tgz";
        sha512 = "+04Z1RHbbz0ldDbHKQFOzveCdI9Rd3TZZu7fno5hHy3OsqTo9UK5Jgqo68wMvRovCO99POv6oCEyO7+urGeN8Q==";
      };
    };
    "@prettier/plugin-ruby-1.6.1" = {
      name = "_at_prettier_slash_plugin-ruby";
      packageName = "@prettier/plugin-ruby";
      version = "1.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@prettier/plugin-ruby/-/plugin-ruby-1.6.1.tgz";
        sha512 = "PGDCATgVTQz0s/NB9nStiXVCIr+hG/XnKeAO/kguaHrNf8VwCpP5Ul+/KQao0z0QFBy2PDY8kWptfDQCa7WMXg==";
      };
    };
    "@prisma/prisma-schema-wasm-4.17.0-26.6b0aef69b7cdfc787f822ecd7cdc76d5f1991584" = {
      name = "_at_prisma_slash_prisma-schema-wasm";
      packageName = "@prisma/prisma-schema-wasm";
      version = "4.17.0-26.6b0aef69b7cdfc787f822ecd7cdc76d5f1991584";
      src = fetchurl {
        url = "https://registry.npmjs.org/@prisma/prisma-schema-wasm/-/prisma-schema-wasm-4.17.0-26.6b0aef69b7cdfc787f822ecd7cdc76d5f1991584.tgz";
        sha512 = "JFdsnSgBPN8reDTLOI9Vh/6ccCb2aD1LbY/LWQnkcIgNo6IdpzvuM+qRVbBuA6IZP2SdqQI8Lu6RL2P8EFBQUA==";
      };
    };
    "@reteps/dockerfmt-0.3.6" = {
      name = "_at_reteps_slash_dockerfmt";
      packageName = "@reteps/dockerfmt";
      version = "0.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@reteps/dockerfmt/-/dockerfmt-0.3.6.tgz";
        sha512 = "Tb5wIMvBf/nLejTQ61krK644/CEMB/cpiaIFXqGApfGqO3GwcR3qnI0DbmkFVCl2OyEp8LnLX3EkucoL0+tbFg==";
      };
    };
    "@sideway/address-4.1.5" = {
      name = "_at_sideway_slash_address";
      packageName = "@sideway/address";
      version = "4.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sideway/address/-/address-4.1.5.tgz";
        sha512 = "IqO/DUQHUkPeixNQ8n0JA6102hT9CmaljNTPmQ1u8MEhBo/R4Q8eKLN/vGZxuebwOroDB4cbpjheD4+/sKFK4Q==";
      };
    };
    "@sideway/formula-3.0.1" = {
      name = "_at_sideway_slash_formula";
      packageName = "@sideway/formula";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sideway/formula/-/formula-3.0.1.tgz";
        sha512 = "/poHZJJVjx3L+zVD6g9KgHfYnb443oi7wLu/XKojDviHy6HOEOA6z1Trk5aR1dGcmPenJEgb2sK2I80LeS3MIg==";
      };
    };
    "@sideway/pinpoint-2.0.0" = {
      name = "_at_sideway_slash_pinpoint";
      packageName = "@sideway/pinpoint";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sideway/pinpoint/-/pinpoint-2.0.0.tgz";
        sha512 = "RNiOoTPkptFtSVzQevY/yWtZwf/RxyVnPy/OcA9HBM3MlGDnBEYL5B41H0MTn0Uec8Hi+2qUtTfG2WWZBmMejQ==";
      };
    };
    "@solidity-parser/parser-0.20.2" = {
      name = "_at_solidity-parser_slash_parser";
      packageName = "@solidity-parser/parser";
      version = "0.20.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@solidity-parser/parser/-/parser-0.20.2.tgz";
        sha512 = "rbu0bzwNvMcwAjH86hiEAcOeRI2EeK8zCkHDrFykh/Al8mvJeFmjy3UrE7GYQjNwOgbGUUtCn5/k8CB8zIu7QA==";
      };
    };
    "@sveltejs/acorn-typescript-1.0.5" = {
      name = "_at_sveltejs_slash_acorn-typescript";
      packageName = "@sveltejs/acorn-typescript";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sveltejs/acorn-typescript/-/acorn-typescript-1.0.5.tgz";
        sha512 = "IwQk4yfwLdibDlrXVE04jTZYlLnwsTT2PIOQQGNLWfjavGifnk1JD1LcZjZaBTRcxZu2FfPfNLOE04DSu9lqtQ==";
      };
    };
    "@taplo/core-0.2.0" = {
      name = "_at_taplo_slash_core";
      packageName = "@taplo/core";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@taplo/core/-/core-0.2.0.tgz";
        sha512 = "r8bl54Zj1In3QLkiW/ex694bVzpPJ9EhwqT9xkcUVODnVUGirdB1JTsmiIv0o1uwqZiwhi8xNnTOQBRQCpizrQ==";
      };
    };
    "@taplo/lib-0.5.0" = {
      name = "_at_taplo_slash_lib";
      packageName = "@taplo/lib";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@taplo/lib/-/lib-0.5.0.tgz";
        sha512 = "+xIqpQXJco3T+VGaTTwmhxLa51qpkQxCjRwezjFZgr+l21ExlywJFcDfTrNmL6lG6tqb0h8GyJKO3UPGPtSCWg==";
      };
    };
    "@types/estree-1.0.8" = {
      name = "_at_types_slash_estree";
      packageName = "@types/estree";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/estree/-/estree-1.0.8.tgz";
        sha512 = "dWHzHa2WqEXI/O1E9OjrocMTKJl2mSrEolh1Iomrv6U+JuNwaHXsXx9bLu5gG7BUWFIN0skIQJQ/L1rIex4X6w==";
      };
    };
    "@types/pegjs-0.10.6" = {
      name = "_at_types_slash_pegjs";
      packageName = "@types/pegjs";
      version = "0.10.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/pegjs/-/pegjs-0.10.6.tgz";
        sha512 = "eLYXDbZWXh2uxf+w8sXS8d6KSoXTswfps6fvCUuVAGN8eRpfe7h9eSRydxiSJvo9Bf+GzifsDOr9TMQlmJdmkw==";
      };
    };
    "@types/uuid-9.0.1" = {
      name = "_at_types_slash_uuid";
      packageName = "@types/uuid";
      version = "9.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/uuid/-/uuid-9.0.1.tgz";
        sha512 = "rFT3ak0/2trgvp4yYZo5iKFEPsET7vKydKF+VRCxlQ9bpheehyAJH89dAkaLEq/j/RZXJIqcgsmPJKUP1Z28HA==";
      };
    };
    "@types/uuid-9.0.6" = {
      name = "_at_types_slash_uuid";
      packageName = "@types/uuid";
      version = "9.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/uuid/-/uuid-9.0.6.tgz";
        sha512 = "BT2Krtx4xaO6iwzwMFUYvWBWkV2pr37zD68Vmp1CDV196MzczBRxuEpD6Pr395HAgebC/co7hOphs53r8V7jew==";
      };
    };
    "@xml-tools/parser-1.0.11" = {
      name = "_at_xml-tools_slash_parser";
      packageName = "@xml-tools/parser";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@xml-tools/parser/-/parser-1.0.11.tgz";
        sha512 = "aKqQ077XnR+oQtHJlrAflaZaL7qZsulWc/i/ZEooar5JiWj1eLt0+Wg28cpa+XLney107wXqneC+oG1IZvxkTA==";
      };
    };
    "acorn-7.4.1" = {
      name = "acorn";
      packageName = "acorn";
      version = "7.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-7.4.1.tgz";
        sha512 = "nQyp0o1/mNdbTO1PO6kHkwSrmgZ0MT/jCCpNiwbUjGoRN4dlBhqJtoQuCnEOKzgTVwg0ZWiCoQy6SxMebQVh8A==";
      };
    };
    "acorn-8.15.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "8.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-8.15.0.tgz";
        sha512 = "NZyJarBfL7nWwIq+FDL6Zp/yHEhePMNnnJ0y3qfieCrmNvYct8uvtiV41UvlSe6apAfk0fY1FbWx+NwfmpvtTg==";
      };
    };
    "argparse-2.0.1" = {
      name = "argparse";
      packageName = "argparse";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-2.0.1.tgz";
        sha512 = "8+9WqebbFzpX9OR+Wa6O29asIogeRMzcGtAINdpMHHyAg10f05aSFVBbcEqGf/PXw1EjAZ+q2/bEBg3DvurK3Q==";
      };
    };
    "aria-query-5.3.2" = {
      name = "aria-query";
      packageName = "aria-query";
      version = "5.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/aria-query/-/aria-query-5.3.2.tgz";
        sha512 = "COROpnaoap1E2F000S62r6A60uHZnmlvomhfyT2DlTcrY1OrBKn2UhH7qn5wTC9zMvD0AY7csdPSNwKP+7WiQw==";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha512 = "NfJ4UzBCcQGLDlQq7nHxH+tv3kyZ0hHQqF5BO6J7tNJeP5do1llPr8dZ8zHonfhAu0PHAdMkSo+8o0wxg9lZWw==";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha512 = "Oei9OH4tRh0YqU3GxhX79dM/mwVgvbZJaSNaRk+bshkj0S5cfHcgYakreBjrHwatXKbz+IoIdYLxrKim2MjW0Q==";
      };
    };
    "axios-1.11.0" = {
      name = "axios";
      packageName = "axios";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/axios/-/axios-1.11.0.tgz";
        sha512 = "1Lx3WLFQWm3ooKDYZD1eXmoGO9fxYQjrycfHFC8P0sCfQVXyROp0p9PFWBehewBOdCwHc+f/b8I0fMto5eSfwA==";
      };
    };
    "axobject-query-4.1.0" = {
      name = "axobject-query";
      packageName = "axobject-query";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/axobject-query/-/axobject-query-4.1.0.tgz";
        sha512 = "qIj0G9wZbMGNLjLmg1PT6v2mE9AH2zlnADJD/2tC6E00hgmhUOfEB6greHPAfLRSufHqROIUTkw6E+M3lH0PTQ==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "big-integer-1.6.52" = {
      name = "big-integer";
      packageName = "big-integer";
      version = "1.6.52";
      src = fetchurl {
        url = "https://registry.npmjs.org/big-integer/-/big-integer-1.6.52.tgz";
        sha512 = "QxD8cf2eVqJOOz63z6JIN9BzvVs/dlySa5HGSBH5xtR8dPteIRQnBxxKqkNTiT6jbDTF6jAfrd4oMcND9RGbQg==";
      };
    };
    "brace-expansion-1.1.12" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.12.tgz";
        sha512 = "9T9UjW3r0UW5c1Q7GTwllptXwhvYmEzFhzMfZ9H7FQWt+uZePjZPjBP/W1ZEyZ1twGWom5/56TF4lPcqjnDHcg==";
      };
    };
    "call-bind-apply-helpers-1.0.2" = {
      name = "call-bind-apply-helpers";
      packageName = "call-bind-apply-helpers";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/call-bind-apply-helpers/-/call-bind-apply-helpers-1.0.2.tgz";
        sha512 = "Sp1ablJ0ivDkSzjcaJdxEunN5/XvksFJ2sMBFfq6x0ryhQV/2b/KwFe21cMpmHtPOSij8K99/wSfoEuTObmuMQ==";
      };
    };
    "call-bound-1.0.4" = {
      name = "call-bound";
      packageName = "call-bound";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/call-bound/-/call-bound-1.0.4.tgz";
        sha512 = "+ys997U96po4Kx/ABpBCqhA9EuxJaQWDQg7295H4hBphv3IZg0boBKuwYpt4YXp6MZ5AmZQnU/tyMTlRpaSejg==";
      };
    };
    "character-parser-2.2.0" = {
      name = "character-parser";
      packageName = "character-parser";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-parser/-/character-parser-2.2.0.tgz";
        sha512 = "+UqJQjFEFaTAs3bNsF2j2kEN1baG/zghZbdqoYEDxGZtJo9LBzl1A+m0D4n3qKx8N2FNv8/Xp6yV9mQmBuptaw==";
      };
    };
    "chevrotain-10.5.0" = {
      name = "chevrotain";
      packageName = "chevrotain";
      version = "10.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chevrotain/-/chevrotain-10.5.0.tgz";
        sha512 = "Pkv5rBY3+CsHOYfV5g/Vs5JY9WTHHDEKOlohI2XeygaZhUeqhAlldZ8Hz9cRmxu709bvS08YzxHdTPHhffc13A==";
      };
    };
    "chevrotain-7.1.1" = {
      name = "chevrotain";
      packageName = "chevrotain";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/chevrotain/-/chevrotain-7.1.1.tgz";
        sha512 = "wy3mC1x4ye+O+QkEinVJkPf5u2vsrDIYW9G7ZuwFl6v/Yu0LwUuT2POsb+NUWApebyxfkQq6+yDfRExbnI5rcw==";
      };
    };
    "class-transformer-0.5.1" = {
      name = "class-transformer";
      packageName = "class-transformer";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/class-transformer/-/class-transformer-0.5.1.tgz";
        sha512 = "SQa1Ws6hUbfC98vKGxZH3KFY0Y1lm5Zm0SY8XX9zbK7FJCyVEac3ATW0RIpwzW+oOfmHE5PMPufDG9hCfoEOMw==";
      };
    };
    "clsx-2.1.1" = {
      name = "clsx";
      packageName = "clsx";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/clsx/-/clsx-2.1.1.tgz";
        sha512 = "eYm0QWBtUrBWZWG0d386OGAw16Z995PiOVo2B7bjWSbHedGl5e0ZWaq65kOGgUSNesEIDkB9ISbTg/JK9dhCZA==";
      };
    };
    "colorette-2.0.20" = {
      name = "colorette";
      packageName = "colorette";
      version = "2.0.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/colorette/-/colorette-2.0.20.tgz";
        sha512 = "IfEDxwoWIjkeXL1eXcDiow4UbKjhLdq6/EuSVR9GMN7KVH3r9gQ83e73hsz1Nd1T3ijd5xv1wcWRYO+D6kCI2w==";
      };
    };
    "combined-stream-1.0.8" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.8.tgz";
        sha512 = "FQN4MRfuJeHf7cBbBMJFXhKSDq+2kAArBlmRBvcvFE5BB1HZKXtSFASDhdlz9zOYwxh8lDdnvmMOe/+5cdoEdg==";
      };
    };
    "commander-2.20.3" = {
      name = "commander";
      packageName = "commander";
      version = "2.20.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.20.3.tgz";
        sha512 = "GpVkmM8vF2vQUkj2LvZmD35JxeJOLCwJ9cUkugyk2nuhbv3+mJvpLYYt+0+USMxE+oj+ey/lJEnhZw75x/OMcQ==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha512 = "/Srv4dswyQNBfohGpz9o6Yb3Gz3SrUDqBH5rTuhGR7ahtlbYKnVxw2bCFMRljaA7EXHaXZ8wsHdodFvbkhKmqg==";
      };
    };
    "cross-spawn-7.0.6" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "7.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.6.tgz";
        sha512 = "uV2QOWP2nWzsy2aMp8aRibhi9dlzF5Hgh5SHaB9OiTGEyDTiJJyx0uy51QXdyWbtAHNua4XJzUKca3OzKUd3vA==";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha512 = "ZySD7Nf91aLB0RxL4KGrKHBXl7Eds1DAmEdcoVawXnLD7SDhpNgtuII2aAkg7a7QS41jxPSZ17p4VdGnMHk3MQ==";
      };
    };
    "detect-newline-3.1.0" = {
      name = "detect-newline";
      packageName = "detect-newline";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/detect-newline/-/detect-newline-3.1.0.tgz";
        sha512 = "TLz+x/vEXm/Y7P7wn1EJFNLxYpUD4TgMosxY6fAVJUnJMbupHBOncxyWUG9OpTaH9EBD7uFI5LfEgmMOc54DsA==";
      };
    };
    "discontinuous-range-1.0.0" = {
      name = "discontinuous-range";
      packageName = "discontinuous-range";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/discontinuous-range/-/discontinuous-range-1.0.0.tgz";
        sha512 = "c68LpLbO+7kP/b1Hr1qs8/BJ09F5khZGTxqxZuhzxpmwJKOgRFHJWIb9/KmqnqHhLdO55aOxFH/EGBvUQbL/RQ==";
      };
    };
    "djv-2.1.4" = {
      name = "djv";
      packageName = "djv";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/djv/-/djv-2.1.4.tgz";
        sha512 = "giDn+BVbtLlwtkvtcsZjbjzpALHB77skiv3FIu6Wp8b5j8BunDcVJYH0cGUaexp6s0Sb7IkquXXjsLBJhXwQpA==";
      };
    };
    "dot-properties-1.1.0" = {
      name = "dot-properties";
      packageName = "dot-properties";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dot-properties/-/dot-properties-1.1.0.tgz";
        sha512 = "uyyuVNX+wq1lTrmLO9iJJAX/vpJ57uppiXQpsd4j1y6NAtHkhCROA4si4mTZMTRshCbcLC1+EMXWZV2MPHUl9A==";
      };
    };
    "dunder-proto-1.0.1" = {
      name = "dunder-proto";
      packageName = "dunder-proto";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dunder-proto/-/dunder-proto-1.0.1.tgz";
        sha512 = "KIN/nDJBQRcXw0MLVhZE9iQHmG68qAVIBg9CqmUYjmQIhgij9U5MFvrqkUL5FbtyyzZuOeOt0zdeRe4UY7ct+A==";
      };
    };
    "elm-format-0.8.7" = {
      name = "elm-format";
      packageName = "elm-format";
      version = "0.8.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/elm-format/-/elm-format-0.8.7.tgz";
        sha512 = "sVzFXfWnb+6rzXK+q3e3Ccgr6/uS5mFbFk1VSmigC+x2XZ28QycAa7lS8owl009ALPhRQk+pZ95Eq5ANjpEZsQ==";
      };
    };
    "es-define-property-1.0.1" = {
      name = "es-define-property";
      packageName = "es-define-property";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-define-property/-/es-define-property-1.0.1.tgz";
        sha512 = "e3nRfgfUZ4rNGL232gUgX06QNyyez04KdjFrF+LTRoOXmrOgFKDg4BCdsjW8EnT69eqdYGmRpJwiPVYNrCaW3g==";
      };
    };
    "es-errors-1.3.0" = {
      name = "es-errors";
      packageName = "es-errors";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-errors/-/es-errors-1.3.0.tgz";
        sha512 = "Zf5H2Kxt2xjTvbJvP2ZWLEICxA6j+hAmMzIlypy4xcBg1vKVnx89Wy0GbS+kf5cwCVFFzdCFh2XSCFNULS6csw==";
      };
    };
    "es-object-atoms-1.1.1" = {
      name = "es-object-atoms";
      packageName = "es-object-atoms";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-object-atoms/-/es-object-atoms-1.1.1.tgz";
        sha512 = "FGgH2h8zKNim9ljj7dankFPcICIK9Cp5bm+c2gQSYePhpaG5+esrLODihIorn+Pe6FGJzWhXQotPv73jTaldXA==";
      };
    };
    "es-set-tostringtag-2.1.0" = {
      name = "es-set-tostringtag";
      packageName = "es-set-tostringtag";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-set-tostringtag/-/es-set-tostringtag-2.1.0.tgz";
        sha512 = "j6vWzfrGVfyXxge+O0x5sh6cvxAog0a/4Rdd2K36zCMV5eJ+/+tOAngRO8cODMNWbVRdVlmGZQL2YS3yR8bIUA==";
      };
    };
    "esm-env-1.2.2" = {
      name = "esm-env";
      packageName = "esm-env";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/esm-env/-/esm-env-1.2.2.tgz";
        sha512 = "Epxrv+Nr/CaL4ZcFGPJIYLWFom+YeV1DqMLHJoEd9SYRxNbaFruBwfEX/kkHUJf55j2+TUbmDcmuilbP1TmXHA==";
      };
    };
    "esrap-2.1.0" = {
      name = "esrap";
      packageName = "esrap";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/esrap/-/esrap-2.1.0.tgz";
        sha512 = "yzmPNpl7TBbMRC5Lj2JlJZNPml0tzqoqP5B1JXycNUwtqma9AKCO0M2wHrdgsHcy1WRW7S9rJknAMtByg3usgA==";
      };
    };
    "execa-5.1.1" = {
      name = "execa";
      packageName = "execa";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/execa/-/execa-5.1.1.tgz";
        sha512 = "8uSpZZocAZRBAPIEINJj3Lo9HyGitllczc27Eh5YYojjMFMn8yHMDMaUHE2Jqfq05D/wucwI4JGURyXt1vchyg==";
      };
    };
    "extsprintf-1.4.1" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.4.1.tgz";
        sha512 = "Wrk35e8ydCKDj/ArClo1VrPVmN8zph5V4AtHwIuHhvMXsKf73UT3BOD+azBIW+3wOJ4FhEH7zyaJCFvChjYvMA==";
      };
    };
    "follow-redirects-1.15.11" = {
      name = "follow-redirects";
      packageName = "follow-redirects";
      version = "1.15.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/follow-redirects/-/follow-redirects-1.15.11.tgz";
        sha512 = "deG2P0JfjrTxl50XGCDyfI97ZGVCxIpfKYmfyrQ54n5FO/0gfIES8C/Psl6kWVDolizcaaxZJnTS0QSMxvnsBQ==";
      };
    };
    "form-data-4.0.4" = {
      name = "form-data";
      packageName = "form-data";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-4.0.4.tgz";
        sha512 = "KrGhL9Q4zjj0kiUt5OO4Mr/A/jlI2jDYs5eHBpYHPcBEVSiipAvn2Ko2HnPe20rmcuuvMHNdZFp+4IlGTMF0Ow==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha512 = "OO0pH2lK6a0hZnAdau5ItzHPI6pUlvI7jMVnxUQRtw4owF2wk8lOSabtGDCTP4Ggrg2MbGnWO9X8K1t4+fGMDw==";
      };
    };
    "function-bind-1.1.2" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.2.tgz";
        sha512 = "7XHNxH7qX9xG5mIwxkhumTox/MIRNcOgDrxWsMt2pAr23WHp6MrRlN7FBSFpCpr+oVO0F744iUgR82nJMfG2SA==";
      };
    };
    "get-intrinsic-1.3.0" = {
      name = "get-intrinsic";
      packageName = "get-intrinsic";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-intrinsic/-/get-intrinsic-1.3.0.tgz";
        sha512 = "9fSjSaos/fRIVIp+xSJlE6lfwhES7LNtKaCBIamHsjr2na1BiABJPo0mOjjz8GJDURarmCPGqaiVg5mfjb98CQ==";
      };
    };
    "get-proto-1.0.1" = {
      name = "get-proto";
      packageName = "get-proto";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-proto/-/get-proto-1.0.1.tgz";
        sha512 = "sTSfBjoXBp89JvIKIefqw7U2CCebsc74kiY6awiGogKtoSGbgjYE/G/+l9sF3MWFPNc9IcoOC4ODfKHfxFmp0g==";
      };
    };
    "get-stream-6.0.1" = {
      name = "get-stream";
      packageName = "get-stream";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stream/-/get-stream-6.0.1.tgz";
        sha512 = "ts6Wi+2j3jQjqi70w5AlN8DFnkSwC+MqmxEzdEALB2qXZYV3X/b1CTfgPLGJNMeAWxdPfU8FO1ms3NUfaHCPYg==";
      };
    };
    "glob-7.2.3" = {
      name = "glob";
      packageName = "glob";
      version = "7.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.2.3.tgz";
        sha512 = "nFR0zLpU2YCaRxwoCJvL6UvCH2JFyFVIvwTLsIf21AuHlMskA1hhTdk+LlYJtOlYt9v6dvszD2BGRqBL+iQK9Q==";
      };
    };
    "gopd-1.2.0" = {
      name = "gopd";
      packageName = "gopd";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/gopd/-/gopd-1.2.0.tgz";
        sha512 = "ZUKRh6/kUFoAiTAtTYPZJ3hw9wNxx+BIBOijnlG9PnrJsCcSjs1wyyD6vJpaYtgnzDrKYRSqf3OO6Rfa93xsRg==";
      };
    };
    "has-symbols-1.1.0" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.1.0.tgz";
        sha512 = "1cDNdwJ2Jaohmb3sg4OmKaMBwuC48sYni5HUw2DvsC8LjGTLK9h+eb1X6RyuOHe4hT0ULCW68iomhjUoKUqlPQ==";
      };
    };
    "has-tostringtag-1.0.2" = {
      name = "has-tostringtag";
      packageName = "has-tostringtag";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-tostringtag/-/has-tostringtag-1.0.2.tgz";
        sha512 = "NqADB8VjPFLM2V0VvHUewwwsw0ZWBaIdgo+ieHtK3hasLz4qeCRjYcqfB6AQrBggRKppKF8L52/VqdVsO47Dlw==";
      };
    };
    "hasown-2.0.2" = {
      name = "hasown";
      packageName = "hasown";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hasown/-/hasown-2.0.2.tgz";
        sha512 = "0hJU9SCPvmMzIBdZFqNPXWa6dqh7WdH0cII9y+CyS8rG3nL48Bclra9HmKhVVUHyPWNH5Y7xDwAB7bfgSjkUMQ==";
      };
    };
    "human-signals-2.1.0" = {
      name = "human-signals";
      packageName = "human-signals";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/human-signals/-/human-signals-2.1.0.tgz";
        sha512 = "B4FFZ6q/T2jhhksgkbEW3HBvWIfDW85snkQgawt07S7J5QXTk6BkNV+0yAeZrM5QpMAdYlocGoljn0sJ/WQkFw==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha512 = "k92I/b08q4wvFscXCLvqfsHCrjrF7yiXsQuIVvVE7N82W3+aqpzuUdBbfhWcy/FZR3/4IgflMgKLOsvPDrGCJA==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "is-expression-4.0.0" = {
      name = "is-expression";
      packageName = "is-expression";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-expression/-/is-expression-4.0.0.tgz";
        sha512 = "zMIXX63sxzG3XrkHkrAPvm/OVZVSCPNkwMHU8oTX7/U3AL78I0QXCEICXUM13BIa8TYGZ68PiTKfQz3yaTNr4A==";
      };
    };
    "is-reference-3.0.3" = {
      name = "is-reference";
      packageName = "is-reference";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-reference/-/is-reference-3.0.3.tgz";
        sha512 = "ixkJoqQvAP88E6wLydLGGqCJsrFUnqoH6HnaczB8XmDH1oaWU+xxdptvikTgaEhtZ53Ky6YXiBuUI2WXLMCwjw==";
      };
    };
    "is-regex-1.2.1" = {
      name = "is-regex";
      packageName = "is-regex";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-regex/-/is-regex-1.2.1.tgz";
        sha512 = "MjYsKHO5O7mCsmRGxWcLWheFqN9DJ/2TmngvjKXihe6efViPqc274+Fx/4fYj/r03+ESvBdTXK0V6tA3rgez1g==";
      };
    };
    "is-stream-2.0.1" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-2.0.1.tgz";
        sha512 = "hFoiJiTl63nn+kstHGBtewWSKnQLpyb155KHheA1l39uvtO9nWIop1p3udqPcUd/xbF1VLMO4n7OI6p7RbngDg==";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha512 = "RHxMLp9lnKHGHRng9QFhRCMbYAcVpn69smSGcq3f36xjgVVWThj4qqLbTLlq7Ssj8B+fIQ1EuCEGI2lKsyQeIw==";
      };
    };
    "jest-docblock-29.7.0" = {
      name = "jest-docblock";
      packageName = "jest-docblock";
      version = "29.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jest-docblock/-/jest-docblock-29.7.0.tgz";
        sha512 = "q617Auw3A612guyaFgsbFeYpNP5t2aoUNLwBUbc/0kD1R4t9ixDbyFTHd1nok4epoVFpr7PmeWHrhvuV3XaJ4g==";
      };
    };
    "jinx-rust-0.1.6" = {
      name = "jinx-rust";
      packageName = "jinx-rust";
      version = "0.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/jinx-rust/-/jinx-rust-0.1.6.tgz";
        sha512 = "qP+wtQL1PrDDFwtPKhNGtjWOmijCrKdfUHWTV2G/ikxfjrh+cjdvkQTmny9RAsVF0jiui9m+F0INWu4cuRcZeQ==";
      };
    };
    "joi-17.13.3" = {
      name = "joi";
      packageName = "joi";
      version = "17.13.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/joi/-/joi-17.13.3.tgz";
        sha512 = "otDA4ldcIx+ZXsKHWmp0YizCweVRZG96J10b0FevjfuncLO1oX59THoAmHkNubYJ+9gWsYsp5k8v4ib6oDv1fA==";
      };
    };
    "jsonata-2.1.0" = {
      name = "jsonata";
      packageName = "jsonata";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonata/-/jsonata-2.1.0.tgz";
        sha512 = "OCzaRMK8HobtX8fp37uIVmL8CY1IGc/a6gLsDqz3quExFR09/U78HUzWYr7T31UEB6+Eu0/8dkVD5fFDOl9a8w==";
      };
    };
    "jsox-1.2.123" = {
      name = "jsox";
      packageName = "jsox";
      version = "1.2.123";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsox/-/jsox-1.2.123.tgz";
        sha512 = "LYordXJ/0Q4G8pUE1Pvh4fkfGvZY7lRe4WIJKl0wr0rtFDVw9lcdNW95GH0DceJ6E9xh41zJNW0vreEz7xOxCw==";
      };
    };
    "linguist-languages-8.1.0" = {
      name = "linguist-languages";
      packageName = "linguist-languages";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/linguist-languages/-/linguist-languages-8.1.0.tgz";
        sha512 = "mg7zk9Lz89MJYvie41yUTmgeMwhN53gKQigNU1i+1JAGNqGRvF59RLhhkKCRYfZLt3rVgWcVSRrj0fxug5R98A==";
      };
    };
    "locate-character-3.0.0" = {
      name = "locate-character";
      packageName = "locate-character";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/locate-character/-/locate-character-3.0.0.tgz";
        sha512 = "SW13ws7BjaeJ6p7Q6CO2nchbYEc3X3J6WrmTTDto7yMPqVSZTUyY5Tjbid+Ab8gLnATtygYtiDIJGQRRn2ZOiA==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "magic-string-0.30.18" = {
      name = "magic-string";
      packageName = "magic-string";
      version = "0.30.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/magic-string/-/magic-string-0.30.18.tgz";
        sha512 = "yi8swmWbO17qHhwIBNeeZxTceJMeBvWJaId6dyvTSOwTipqeHhMhOrz6513r1sOKnpvQ7zkhlG8tPrpilwTxHQ==";
      };
    };
    "make-dir-3.1.0" = {
      name = "make-dir";
      packageName = "make-dir";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/make-dir/-/make-dir-3.1.0.tgz";
        sha512 = "g3FeP20LNwhALb/6Cz6Dd4F2ngze0jz7tbzrD2wAV+o9FeNHe4rL+yK2md0J/fiSf1sa1ADhXqi5+oVwOM/eGw==";
      };
    };
    "math-intrinsics-1.1.0" = {
      name = "math-intrinsics";
      packageName = "math-intrinsics";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/math-intrinsics/-/math-intrinsics-1.1.0.tgz";
        sha512 = "/IXtbwEk5HTPyEwyKX6hGkYXxM9nbj64B+ilVJnC/R6B0pH5G4V3b0pVbL7DBj4tkhBAppbQUlf6F6Xl9LHu1g==";
      };
    };
    "merge-stream-2.0.0" = {
      name = "merge-stream";
      packageName = "merge-stream";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-stream/-/merge-stream-2.0.0.tgz";
        sha512 = "abv/qOcuPfk3URPfDzmZU1LKmuw8kT+0nIHvKrKgFrwifol/doWcdA4ZqsWQ8ENrFKkd67Mfpo/LovbIUsbt3w==";
      };
    };
    "mime-db-1.52.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.52.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.52.0.tgz";
        sha512 = "sPU4uV7dYlvtWJxwwxHD0PuihVNiE7TyAbQ5SWxDCB9mUYvOgroQOwYQQOKPJ8CIbE+1ETVlOoK1UC2nU3gYvg==";
      };
    };
    "mime-types-2.1.35" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.35";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.35.tgz";
        sha512 = "ZDY+bPm5zTTF+YpCrAU9nK0UgICYPT0QtT1NZWFv4s++TNkcgVaT0g6+4R2uI4MjQjzysHB1zxuWL50hzaeXiw==";
      };
    };
    "mimic-fn-2.1.0" = {
      name = "mimic-fn";
      packageName = "mimic-fn";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mimic-fn/-/mimic-fn-2.1.0.tgz";
        sha512 = "OqbOk5oEQeAZ8WXWydlu9HJjz9WVdEIvamMCcXmuqUYjTknH/sqsWvhQ3vgwKFRR1HpjvNBKQ37nbJgYzGqGcg==";
      };
    };
    "minimatch-3.1.2" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.1.2.tgz";
        sha512 = "J7p63hRiAjw1NDEww1W7i37+ByIrOWO5XQQAzZ3VOcL0PNybwpfmV/N05zFAzwQ9USyEcX6t3UO+K5aqBQOIHw==";
      };
    };
    "minimist-1.2.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.8.tgz";
        sha512 = "2yyAR8qBkN3YuheJanUpWC5U3bb5osDywNB8RzDVlDwDHbocAJveqqj1u8+SVD7jkWT4yvsHCpWqqWqAxb0zCA==";
      };
    };
    "moo-0.5.2" = {
      name = "moo";
      packageName = "moo";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/moo/-/moo-0.5.2.tgz";
        sha512 = "iSAJLHYKnX41mKcJKjqvnAN9sf0LMDTXDEvFv+ffuRR9a1MIuXLjMNL6EsnDHSkKLTWNqQQ5uo61P4EbU4NU+Q==";
      };
    };
    "nearley-2.20.1" = {
      name = "nearley";
      packageName = "nearley";
      version = "2.20.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/nearley/-/nearley-2.20.1.tgz";
        sha512 = "+Mc8UaAebFzgV+KpI5n7DasuuQCHA89dmwm7JXw3TV43ukfNQ9DnBH3Mdb2g/I4Fdxc26pwimBWvjIw0UAILSQ==";
      };
    };
    "node-sql-parser-5.3.11" = {
      name = "node-sql-parser";
      packageName = "node-sql-parser";
      version = "5.3.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-sql-parser/-/node-sql-parser-5.3.11.tgz";
        sha512 = "1ZcXu2qEFZlMkkaYPpMoTkypTunYTvtnInzVjWDhjc1+FS5h/WqT1rbgP2pP42/nXBWfPVN66mEfidWSpYVs1Q==";
      };
    };
    "npm-run-path-4.0.1" = {
      name = "npm-run-path";
      packageName = "npm-run-path";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-run-path/-/npm-run-path-4.0.1.tgz";
        sha512 = "S48WzZW777zhNIrn7gxOlISNAqi9ZC/uQFnRdbeIHhZhCA6UqpkOT8T1G7BvfdgP4Er8gF4sUbaS0i7QvIfCWw==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha512 = "rJgTQnkUnH1sFw8yT6VSU3zD3sWmu6sZhIseY8VX+GRu3P6F7Fu+JNDoXfklElbLJSnc3FUQHVe4cU5hj+BcUg==";
      };
    };
    "object-hash-3.0.0" = {
      name = "object-hash";
      packageName = "object-hash";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-hash/-/object-hash-3.0.0.tgz";
        sha512 = "RSn9F68PjH9HqtltsSnqYC1XXoWe9Bju5+213R98cNGttag9q9yAOTzdbsqvIa7aNm5WffBZFpWYr2aWrklWAw==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha512 = "lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==";
      };
    };
    "onetime-5.1.2" = {
      name = "onetime";
      packageName = "onetime";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/onetime/-/onetime-5.1.2.tgz";
        sha512 = "kbpaSSGJTWdAY5KPVeMOKXSrPtr8C8C7wodJbcsd51jRnmD+GZu8Y0VoU6Dm5Z4vWr0Ig/1NKuWRKf7j5aaYSg==";
      };
    };
    "out-of-character-1.2.4" = {
      name = "out-of-character";
      packageName = "out-of-character";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/out-of-character/-/out-of-character-1.2.4.tgz";
        sha512 = "2/wkZ8i3b1jLeYbHI+jFZBunMQsbBjMZEOlfi/oFtgDuYz7k7etEL3PSa6ZEJKSaJ9RWZpOp8eLnMgovAYTj5w==";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha512 = "AVbw3UJ2e9bq64vSaS9Am0fje1Pa8pbGqTTsmXfaIiMpnr5DlDhfJOuLj9Sf95ZPVDAUerDfEk88MPmPe7UCQg==";
      };
    };
    "path-key-3.1.1" = {
      name = "path-key";
      packageName = "path-key";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz";
        sha512 = "ojmeN0qd+y0jszEtoY48r0Peq5dwMEkIlCOu6Q5f41lfkswXuKtYrhgoTpLnyIcHm24Uhqx+5Tqm2InSwLhE6Q==";
      };
    };
    "php-parser-3.2.5" = {
      name = "php-parser";
      packageName = "php-parser";
      version = "3.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/php-parser/-/php-parser-3.2.5.tgz";
        sha512 = "M1ZYlALFFnESbSdmRtTQrBFUHSriHgPhgqtTF/LCbZM4h7swR5PHtUceB2Kzby5CfqcsYwBn7OXTJ0+8Sajwkw==";
      };
    };
    "prettier-1.19.1" = {
      name = "prettier";
      packageName = "prettier";
      version = "1.19.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier/-/prettier-1.19.1.tgz";
        sha512 = "s7PoyDv/II1ObgQunCbB9PdLmUcBZcnWOcxDh7O0N/UwDEsHyqkW+Qh28jW+mVuCdx7gLB0BotYI1Y6uI9iyew==";
      };
    };
    "prettier-2.2.1" = {
      name = "prettier";
      packageName = "prettier";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier/-/prettier-2.2.1.tgz";
        sha512 = "PqyhM2yCjg/oKkFPtTGUojv7gnZAoG80ttl45O6x2Ug/rMJw4wcc9k6aaf2hibP7BGVCCM33gZoGjyvt9mm16Q==";
      };
    };
    "prettier-2.8.8" = {
      name = "prettier";
      packageName = "prettier";
      version = "2.8.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier/-/prettier-2.8.8.tgz";
        sha512 = "tdN8qQGvNjw4CHbY+XXk0JgCXn9QiF21a55rBe5LJAU+kDyC4WQn4+awm2Xfk2lQMk5fKup9XgzTZtGkjBdP9Q==";
      };
    };
    "prettier-3.6.2" = {
      name = "prettier";
      packageName = "prettier";
      version = "3.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier/-/prettier-3.6.2.tgz";
        sha512 = "I7AIg5boAr5R0FFtJ6rCfD+LFsWHp81dolrFD8S79U9tb8Az2nGrJncnMSnys+bpQJfRUzqs9hnA81OAA3hCuQ==";
      };
    };
    "prettier-html-templates-0.1.0" = {
      name = "prettier-html-templates";
      packageName = "prettier-html-templates";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier-html-templates/-/prettier-html-templates-0.1.0.tgz";
        sha512 = "KdLveYzO2kJLiwUAebd5UFeKP8h3OqFhOiLbkgeIuS1WNoCRTyxW4KuyGfbh3F+Rp/2A6mipRxCq2zPi+//pmg==";
      };
    };
    "proxy-from-env-1.1.0" = {
      name = "proxy-from-env";
      packageName = "proxy-from-env";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-from-env/-/proxy-from-env-1.1.0.tgz";
        sha512 = "D+zkORCbA9f1tdWRK0RaCR3GPv50cMxcrz4X8k5LTSUD1Dkw47mKJEZQNunItRTkWwgtaUSo1RVFRIG9ZXiFYg==";
      };
    };
    "pug-error-2.1.0" = {
      name = "pug-error";
      packageName = "pug-error";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-error/-/pug-error-2.1.0.tgz";
        sha512 = "lv7sU9e5Jk8IeUheHata6/UThZ7RK2jnaaNztxfPYUY+VxZyk/ePVaNZ/vwmH8WqGvDz3LrNYt/+gA55NDg6Pg==";
      };
    };
    "pug-lexer-5.0.1" = {
      name = "pug-lexer";
      packageName = "pug-lexer";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-lexer/-/pug-lexer-5.0.1.tgz";
        sha512 = "0I6C62+keXlZPZkOJeVam9aBLVP2EnbeDw3An+k0/QlqdwH6rv8284nko14Na7c0TtqtogfWXcRoFE4O4Ff20w==";
      };
    };
    "railroad-diagrams-1.0.0" = {
      name = "railroad-diagrams";
      packageName = "railroad-diagrams";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/railroad-diagrams/-/railroad-diagrams-1.0.0.tgz";
        sha512 = "cz93DjNeLY0idrCNOH6PviZGRN9GJhsdm9hpn1YCS879fj4W+x5IFJhhkRZcwVgMmFF7R82UA/7Oh+R8lLZg6A==";
      };
    };
    "randexp-0.4.6" = {
      name = "randexp";
      packageName = "randexp";
      version = "0.4.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/randexp/-/randexp-0.4.6.tgz";
        sha512 = "80WNmd9DA0tmZrw9qQa62GPPWfuXJknrmVmLcxvq4uZBdYqb1wYoKTmnlGUchvVWe0XiLupYkBoXVOxz3C8DYQ==";
      };
    };
    "reflect-metadata-0.1.13" = {
      name = "reflect-metadata";
      packageName = "reflect-metadata";
      version = "0.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/reflect-metadata/-/reflect-metadata-0.1.13.tgz";
        sha512 = "Ts1Y/anZELhSsjMcU605fU9RE4Oi3p5ORujwbIKXfWa+0Zxs510Qrmrce5/Jowq3cHSZSJqBjypxmHarc+vEWg==";
      };
    };
    "regexp-to-ast-0.5.0" = {
      name = "regexp-to-ast";
      packageName = "regexp-to-ast";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/regexp-to-ast/-/regexp-to-ast-0.5.0.tgz";
        sha512 = "tlbJqcMHnPKI9zSrystikWKwHkBqu2a/Sgw01h3zFjvYrMxEDYHzzoMZnUrbIfpTFEsoRnnviOXNCzFiSc54Qw==";
      };
    };
    "ret-0.1.15" = {
      name = "ret";
      packageName = "ret";
      version = "0.1.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/ret/-/ret-0.1.15.tgz";
        sha512 = "TTlYpa+OL+vMMNG24xSlQGEJ3B/RzEfUlLct7b5G/ytav+wPrplCpVMFuwzXbkecJrb6IYo1iFb0S9v37754mg==";
      };
    };
    "rxjs-7.8.2" = {
      name = "rxjs";
      packageName = "rxjs";
      version = "7.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rxjs/-/rxjs-7.8.2.tgz";
        sha512 = "dhKf903U/PQZY6boNNtAGdWbG85WAbjT/1xYoZIC7FAY0yWapOBQVsVrDl58W86//e1VpMNBtRV4MaXfdMySFA==";
      };
    };
    "s.color-0.0.15" = {
      name = "s.color";
      packageName = "s.color";
      version = "0.0.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/s.color/-/s.color-0.0.15.tgz";
        sha512 = "AUNrbEUHeKY8XsYr/DYpl+qk5+aM+DChopnWOPEzn8YKzOhv4l2zH6LzZms3tOZP3wwdOyc0RmTciyi46HLIuA==";
      };
    };
    "sass-formatter-0.7.9" = {
      name = "sass-formatter";
      packageName = "sass-formatter";
      version = "0.7.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/sass-formatter/-/sass-formatter-0.7.9.tgz";
        sha512 = "CWZ8XiSim+fJVG0cFLStwDvft1VI7uvXdCNJYXhDvowiv+DsbD1nXLiQ4zrE5UBvj5DWZJ93cwN0NX5PMsr1Pw==";
      };
    };
    "semver-6.3.1" = {
      name = "semver";
      packageName = "semver";
      version = "6.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-6.3.1.tgz";
        sha512 = "BR7VvDCVHO+q2xBEWskxS6DJE1qRnb7DxzUrogb71CWoSficBxYsiAGd+Kl0mmq/MprG9yArRkyrQxTO6XjMzA==";
      };
    };
    "semver-7.7.2" = {
      name = "semver";
      packageName = "semver";
      version = "7.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.7.2.tgz";
        sha512 = "RF0Fw+rO5AMf9MAyaRXI4AV0Ulj5lMHqVxxdSgiVbixSCXoEmmX/jk0CuJw4+3SqroYO9VoUh+HcuJivvtJemA==";
      };
    };
    "serialize-error-8.1.0" = {
      name = "serialize-error";
      packageName = "serialize-error";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/serialize-error/-/serialize-error-8.1.0.tgz";
        sha512 = "3NnuWfM6vBYoy5gZFvHiYsVbafvI9vZv/+jlIigFn4oP4zjNPK3LhcY0xSCgeb1a5L8jO71Mit9LlNoi2UfDDQ==";
      };
    };
    "sh-syntax-0.5.8" = {
      name = "sh-syntax";
      packageName = "sh-syntax";
      version = "0.5.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/sh-syntax/-/sh-syntax-0.5.8.tgz";
        sha512 = "JfVoxf4FxQI5qpsPbkHhZo+n6N9YMJobyl4oGEUBb/31oQYlgTjkXQD8PBiafS2UbWoxrTO0Z5PJUBXEPAG1Zw==";
      };
    };
    "shebang-command-2.0.0" = {
      name = "shebang-command";
      packageName = "shebang-command";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz";
        sha512 = "kHxr2zZpYtdmrN1qDjrrX/Z1rR1kG8Dx+gkpK1G4eXmvXswmcE1hTWBWYUzlraYw1/yZp6YuDY77YtvbN0dmDA==";
      };
    };
    "shebang-regex-3.0.0" = {
      name = "shebang-regex";
      packageName = "shebang-regex";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz";
        sha512 = "7++dFhtcx3353uBaq8DDR4NuxBetBzC7ZQOhmTQInHEd6bSrXdiEyzCvG07Z44UYdLShWUyXt5M/yhz8ekcb1A==";
      };
    };
    "signal-exit-3.0.7" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.7.tgz";
        sha512 = "wnD2ZE+l+SPC/uoS0vXeE9L1+0wuaMqKlfz9AMUo38JsyLSBWSFcHR1Rri62LZc12vLr1gb3jl7iwQhgwpAbGQ==";
      };
    };
    "sql-formatter-15.6.6" = {
      name = "sql-formatter";
      packageName = "sql-formatter";
      version = "15.6.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/sql-formatter/-/sql-formatter-15.6.6.tgz";
        sha512 = "bZydXEXhaNDQBr8xYHC3a8thwcaMuTBp0CkKGjwGYDsIB26tnlWeWPwJtSQ0TEwiJcz9iJJON5mFPkx7XroHcg==";
      };
    };
    "sql-parser-cst-0.33.1" = {
      name = "sql-parser-cst";
      packageName = "sql-parser-cst";
      version = "0.33.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sql-parser-cst/-/sql-parser-cst-0.33.1.tgz";
        sha512 = "7PHLI98bo86S740GQWlerh9GHu10dbMqDo1jBCXVlGB/nc55WgIAeoVrp0jzgK+WikycE9iGUUKkSuFNxj8w3Q==";
      };
    };
    "strip-final-newline-2.0.0" = {
      name = "strip-final-newline";
      packageName = "strip-final-newline";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-final-newline/-/strip-final-newline-2.0.0.tgz";
        sha512 = "BrpvfNAE3dcvq7ll3xVumzjKjZQ5tI1sEUIKr3Uoks0XUl45St3FlatVqef9prk4jRDzhW6WZg+3bk93y6pLjA==";
      };
    };
    "suf-log-2.5.3" = {
      name = "suf-log";
      packageName = "suf-log";
      version = "2.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/suf-log/-/suf-log-2.5.3.tgz";
        sha512 = "KvC8OPjzdNOe+xQ4XWJV2whQA0aM1kGVczMQ8+dStAO6KfEB140JEVQ9dE76ONZ0/Ylf67ni4tILPJB41U0eow==";
      };
    };
    "svelte-5.38.6" = {
      name = "svelte";
      packageName = "svelte";
      version = "5.38.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/svelte/-/svelte-5.38.6.tgz";
        sha512 = "ltBPlkvqk3bgCK7/N323atUpP3O3Y+DrGV4dcULrsSn4fZaaNnOmdplNznwfdWclAgvSr5rxjtzn/zJhRm6TKg==";
      };
    };
    "temp-dir-2.0.0" = {
      name = "temp-dir";
      packageName = "temp-dir";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/temp-dir/-/temp-dir-2.0.0.tgz";
        sha512 = "aoBAniQmmwtcKp/7BzsH8Cxzv8OL736p7v1ihGb5e9DJ9kTwGWHrQrVB5+lfVDzfGrdRzXch+ig7LHaY1JTOrg==";
      };
    };
    "tslib-2.8.1" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.8.1.tgz";
        sha512 = "oJFu94HQb+KVduSUQL7wnpmqnfmLsOA/nAh6b6EH0wCEoK0/mPeXU6c3wKDV83MkOuHPRHtSXKKU99IBazS/2w==";
      };
    };
    "type-fest-0.20.2" = {
      name = "type-fest";
      packageName = "type-fest";
      version = "0.20.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-fest/-/type-fest-0.20.2.tgz";
        sha512 = "Ne+eE4r0/iWnpAxD852z3A+N0Bt5RN//NjJwRd2VFHEmrywxf5vsZlh4R6lixl6B+wz/8d+maTSAkN1FIkI3LQ==";
      };
    };
    "ulid-2.4.0" = {
      name = "ulid";
      packageName = "ulid";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ulid/-/ulid-2.4.0.tgz";
        sha512 = "fIRiVTJNcSRmXKPZtGzFQv9WRrZ3M9eoptl/teFJvjOzmpU+/K/JH6HZ8deBfb5vMEpicJcLn7JmvdknlMq7Zg==";
      };
    };
    "uuid-9.0.0" = {
      name = "uuid";
      packageName = "uuid";
      version = "9.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-9.0.0.tgz";
        sha512 = "MXcSTerfPa4uqyzStbRoTgt5XIe3x5+42+q1sDuy3R5MDk66URdLMOZe5aPX/SQd+kuYAh0FdP/pO28IkQyTeg==";
      };
    };
    "uuid-9.0.1" = {
      name = "uuid";
      packageName = "uuid";
      version = "9.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-9.0.1.tgz";
        sha512 = "b+1eJOlsR9K8HJpow9Ok3fiWOWSIcIzXodvv0rQjVoOVNpWMpxf1wZNpt4y9h10odCNrqnYp1OBzRktckBe3sA==";
      };
    };
    "wait-on-8.0.4" = {
      name = "wait-on";
      packageName = "wait-on";
      version = "8.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/wait-on/-/wait-on-8.0.4.tgz";
        sha512 = "8f9LugAGo4PSc0aLbpKVCVtzayd36sSCp4WLpVngkYq6PK87H79zt77/tlCU6eKCLqR46iFvcl0PU5f+DmtkwA==";
      };
    };
    "which-2.0.2" = {
      name = "which";
      packageName = "which";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
        sha512 = "BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha512 = "l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==";
      };
    };
    "zimmerframe-1.1.2" = {
      name = "zimmerframe";
      packageName = "zimmerframe";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/zimmerframe/-/zimmerframe-1.1.2.tgz";
        sha512 = "rAbqEGa8ovJy4pyBxZM70hg4pE6gDgaQ0Sl9M3enG3I0d6H4XSAM3GeNGLKnsBpuijUow064sf7ww1nutC5/3w==";
      };
    };
  };
in
{
  "@prettier/plugin-php" = nodeEnv.buildNodePackage {
    name = "_at_prettier_slash_plugin-php";
    packageName = "@prettier/plugin-php";
    version = "0.24.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@prettier/plugin-php/-/plugin-php-0.24.0.tgz";
      sha512 = "x9l65fCE/pgoET6RQowgdgG8Xmzs44z6j6Hhg3coINCyCw9JBGJ5ZzMR2XHAM2jmAdbJAIgqB6cUn4/3W3XLTA==";
    };
    dependencies = [
      sources."linguist-languages-8.1.0"
      sources."php-parser-3.2.5"
      sources."prettier-3.6.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Prettier PHP Plugin";
      homepage = "https://github.com/prettier/prettier-php#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@prettier/plugin-pug" = nodeEnv.buildNodePackage {
    name = "_at_prettier_slash_plugin-pug";
    packageName = "@prettier/plugin-pug";
    version = "3.4.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/@prettier/plugin-pug/-/plugin-pug-3.4.2.tgz";
      sha512 = "/VOVeIscKYlPpsZrjrRV+44ZftCEIJq9Z/zR8PtAz/EDv82TKscw3z+fhTVqRz68G1TqQ/5COMFUVfPwPBH90w==";
    };
    dependencies = [
      sources."acorn-7.4.1"
      sources."call-bind-apply-helpers-1.0.2"
      sources."call-bound-1.0.4"
      sources."character-parser-2.2.0"
      sources."dunder-proto-1.0.1"
      sources."es-define-property-1.0.1"
      sources."es-errors-1.3.0"
      sources."es-object-atoms-1.1.1"
      sources."function-bind-1.1.2"
      sources."get-intrinsic-1.3.0"
      sources."get-proto-1.0.1"
      sources."gopd-1.2.0"
      sources."has-symbols-1.1.0"
      sources."has-tostringtag-1.0.2"
      sources."hasown-2.0.2"
      sources."is-expression-4.0.0"
      sources."is-regex-1.2.1"
      sources."math-intrinsics-1.1.0"
      sources."object-assign-4.1.1"
      sources."prettier-3.6.2"
      sources."pug-error-2.1.0"
      sources."pug-lexer-5.0.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Prettier Pug Plugin";
      homepage = "https://github.com/prettier/plugin-pug#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@prettier/plugin-ruby" = nodeEnv.buildNodePackage {
    name = "_at_prettier_slash_plugin-ruby";
    packageName = "@prettier/plugin-ruby";
    version = "4.0.4";
    src = fetchurl {
      url = "https://registry.npmjs.org/@prettier/plugin-ruby/-/plugin-ruby-4.0.4.tgz";
      sha512 = "lCpvfS/dQU5WrwN3AQ5vR8qrvj2h5gE41X08NNzAAXvHdM4zwwGRcP2sHSxfu6n6No+ljWCVx95NvJPFTTjCTg==";
    };
    dependencies = [
      sources."prettier-3.6.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "prettier plugin for the Ruby programming language";
      homepage = "https://github.com/prettier/plugin-ruby#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@prettier/plugin-xml" = nodeEnv.buildNodePackage {
    name = "_at_prettier_slash_plugin-xml";
    packageName = "@prettier/plugin-xml";
    version = "3.4.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/@prettier/plugin-xml/-/plugin-xml-3.4.2.tgz";
      sha512 = "/UyNlHfkuLXG6Ed85KB0WBF283xn2yavR+UtRibBRUcvEJId2DSLdGXwJ/cDa1X++SWDPzq3+GSFniHjkNy7yg==";
    };
    dependencies = [
      sources."@xml-tools/parser-1.0.11"
      sources."chevrotain-7.1.1"
      sources."prettier-3.6.2"
      sources."regexp-to-ast-0.5.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "prettier plugin for XML";
      homepage = "https://github.com/prettier/plugin-xml#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  prettier-plugin-apex = nodeEnv.buildNodePackage {
    name = "prettier-plugin-apex";
    packageName = "prettier-plugin-apex";
    version = "2.2.6";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-apex/-/prettier-plugin-apex-2.2.6.tgz";
      sha512 = "1z1WFl2zy0FDTCTLP9f/78TdEpTJ6qBGAf9vRbT9o4KRXBOfTmWkZiEYV1+QYky8ulxl085iS18JQKUm5K9KPg==";
    };
    dependencies = [
      sources."@hapi/hoek-9.3.0"
      sources."@hapi/topo-5.1.0"
      sources."@sideway/address-4.1.5"
      sources."@sideway/formula-3.0.1"
      sources."@sideway/pinpoint-2.0.0"
      sources."asynckit-0.4.0"
      sources."axios-1.11.0"
      sources."call-bind-apply-helpers-1.0.2"
      sources."combined-stream-1.0.8"
      sources."delayed-stream-1.0.0"
      sources."detect-newline-3.1.0"
      sources."dunder-proto-1.0.1"
      sources."es-define-property-1.0.1"
      sources."es-errors-1.3.0"
      sources."es-object-atoms-1.1.1"
      sources."es-set-tostringtag-2.1.0"
      sources."follow-redirects-1.15.11"
      sources."form-data-4.0.4"
      sources."function-bind-1.1.2"
      sources."get-intrinsic-1.3.0"
      sources."get-proto-1.0.1"
      sources."gopd-1.2.0"
      sources."has-symbols-1.1.0"
      sources."has-tostringtag-1.0.2"
      sources."hasown-2.0.2"
      sources."jest-docblock-29.7.0"
      sources."joi-17.13.3"
      sources."lodash-4.17.21"
      sources."math-intrinsics-1.1.0"
      sources."mime-db-1.52.0"
      sources."mime-types-2.1.35"
      sources."minimist-1.2.8"
      sources."prettier-3.6.2"
      sources."proxy-from-env-1.1.0"
      sources."rxjs-7.8.2"
      sources."tslib-2.8.1"
      sources."wait-on-8.0.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Salesforce Apex plugin for Prettier";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  prettier-plugin-astro = nodeEnv.buildNodePackage {
    name = "prettier-plugin-astro";
    packageName = "prettier-plugin-astro";
    version = "0.14.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-astro/-/prettier-plugin-astro-0.14.1.tgz";
      sha512 = "RiBETaaP9veVstE4vUwSIcdATj6dKmXljouXc/DDNwBSPTp8FRkLGDSGFClKsAFeeg+13SB0Z1JZvbD76bigJw==";
    };
    dependencies = [
      sources."@astrojs/compiler-2.12.2"
      sources."prettier-3.6.2"
      sources."s.color-0.0.15"
      sources."sass-formatter-0.7.9"
      sources."suf-log-2.5.3"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A Prettier Plugin for formatting Astro files";
      homepage = "https://github.com/withastro/prettier-plugin-astro/";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  prettier-plugin-elm = nodeEnv.buildNodePackage {
    name = "prettier-plugin-elm";
    packageName = "prettier-plugin-elm";
    version = "0.11.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-elm/-/prettier-plugin-elm-0.11.0.tgz";
      sha512 = "x4srzUljo5CbeYiyK6EtbEB+1by0b6oUDqJ1l1hfdOOGOPGXfnbGLJK3VFOBEHwk0G4OcBCi8REjrc2NGIAfCQ==";
    };
    dependencies = [
      sources."@avh4/elm-format-darwin-arm64-0.8.7-2"
      sources."@avh4/elm-format-darwin-x64-0.8.7-2"
      sources."@avh4/elm-format-linux-arm64-0.8.7-2"
      sources."@avh4/elm-format-linux-x64-0.8.7-2"
      sources."@avh4/elm-format-win32-x64-0.8.7-2"
      sources."cross-spawn-7.0.6"
      sources."elm-format-0.8.7"
      sources."execa-5.1.1"
      sources."get-stream-6.0.1"
      sources."human-signals-2.1.0"
      sources."is-stream-2.0.1"
      sources."isexe-2.0.0"
      sources."make-dir-3.1.0"
      sources."merge-stream-2.0.0"
      sources."mimic-fn-2.1.0"
      sources."npm-run-path-4.0.1"
      sources."object-hash-3.0.0"
      sources."onetime-5.1.2"
      sources."path-key-3.1.1"
      sources."semver-6.3.1"
      sources."serialize-error-8.1.0"
      sources."shebang-command-2.0.0"
      sources."shebang-regex-3.0.0"
      sources."signal-exit-3.0.7"
      sources."strip-final-newline-2.0.0"
      sources."temp-dir-2.0.0"
      sources."type-fest-0.20.2"
      sources."which-2.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Adds Elm language support to Prettier via elm-format";
      license = "BSD-3-Clause";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  prettier-plugin-erb = nodeEnv.buildNodePackage {
    name = "prettier-plugin-erb";
    packageName = "prettier-plugin-erb";
    version = "0.4.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-erb/-/prettier-plugin-erb-0.4.0.tgz";
      sha512 = "5RAdvT5BBf29hfC8GmqiMRFiD5g4BZGZDERZHvM5ouOor2TVT0jM0ntmCzFpS2Q32OkUAGFYsRxXDoYscvToXA==";
    };
    dependencies = [
      sources."@prettier/plugin-ruby-1.6.1"
      sources."prettier-2.2.1"
      sources."prettier-html-templates-0.1.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Prettier plugin for .html.erb files";
      homepage = "https://github.com/adamzapasnik/prettier-plugin-erb#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  prettier-plugin-gherkin = nodeEnv.buildNodePackage {
    name = "prettier-plugin-gherkin";
    packageName = "prettier-plugin-gherkin";
    version = "3.1.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-gherkin/-/prettier-plugin-gherkin-3.1.2.tgz";
      sha512 = "LgehRNKCAqZsoE/yblmqXYfMpEK2mhVWQKNj/TFzeLR+0rhFGHqq3RlYcYhPgzbr0n6w2Bv+0Gm1yxNdzkdacw==";
    };
    dependencies = [
      (sources."@cucumber/gherkin-27.0.0" // {
        dependencies = [
          sources."@cucumber/messages-22.0.0"
        ];
      })
      (sources."@cucumber/messages-23.0.0" // {
        dependencies = [
          sources."@types/uuid-9.0.6"
          sources."uuid-9.0.1"
        ];
      })
      sources."@types/uuid-9.0.1"
      sources."class-transformer-0.5.1"
      sources."prettier-3.6.2"
      sources."reflect-metadata-0.1.13"
      sources."uuid-9.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "This prettier plugin format your gherkin (`.feature` files) documents.";
      homepage = "https://github.com/mapado/prettier-plugin-gherkin";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  prettier-plugin-glsl = nodeEnv.buildNodePackage {
    name = "prettier-plugin-glsl";
    packageName = "prettier-plugin-glsl";
    version = "0.2.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-glsl/-/prettier-plugin-glsl-0.2.2.tgz";
      sha512 = "VD4A59LtF6Eyw7FS46tOh6ZhVbIrdk3ikEPiFkyOAr8RgnuiL2Ad5EnuDqxYYzBqEPO3xDfhejieF3Q/AL5+7A==";
    };
    dependencies = [
      sources."@chevrotain/cst-dts-gen-10.5.0"
      sources."@chevrotain/gast-10.5.0"
      sources."@chevrotain/types-10.5.0"
      sources."@chevrotain/utils-10.5.0"
      sources."@netflix/nerror-1.1.3"
      sources."assert-plus-1.0.0"
      sources."chevrotain-10.5.0"
      sources."extsprintf-1.4.1"
      sources."lodash-4.17.21"
      sources."prettier-3.6.2"
      sources."regexp-to-ast-0.5.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Prettier (https://prettier.io) plugin for GLSL (OpenGL Shading Language).";
      homepage = "https://github.com/NaridaL/glsl-language-toolkit#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  prettier-plugin-go-template = nodeEnv.buildNodePackage {
    name = "prettier-plugin-go-template";
    packageName = "prettier-plugin-go-template";
    version = "0.0.15";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-go-template/-/prettier-plugin-go-template-0.0.15.tgz";
      sha512 = "WqU92E1NokWYNZ9mLE6ijoRg6LtIGdLMePt2C7UBDjXeDH9okcRI3zRqtnWR4s5AloiqyvZ66jNBAa9tmRY5EQ==";
    };
    dependencies = [
      sources."prettier-3.6.2"
      sources."ulid-2.4.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Prettier plugin for formatting Go & GoHugo templates.";
      homepage = "https://github.com/NiklasPor/prettier-plugin-go-template#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  prettier-plugin-jinja-template = nodeEnv.buildNodePackage {
    name = "prettier-plugin-jinja-template";
    packageName = "prettier-plugin-jinja-template";
    version = "2.1.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-jinja-template/-/prettier-plugin-jinja-template-2.1.0.tgz";
      sha512 = "mzoCp2Oy9BDSug80fw3B3J4n4KQj1hRvoQOL1akqcDKBb5nvYxrik9zUEDs4AEJ6nK7QDTGoH0y9rx7AlnQ78Q==";
    };
    dependencies = [
      sources."prettier-3.6.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Prettier plugin for formatting jinja templates.";
      homepage = "https://github.com/davidodenwald/prettier-plugin-jinja-template#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@stedi/prettier-plugin-jsonata" = nodeEnv.buildNodePackage {
    name = "_at_stedi_slash_prettier-plugin-jsonata";
    packageName = "@stedi/prettier-plugin-jsonata";
    version = "2.1.6";
    src = fetchurl {
      url = "https://registry.npmjs.org/@stedi/prettier-plugin-jsonata/-/prettier-plugin-jsonata-2.1.6.tgz";
      sha512 = "U7C+oisyxk4UsHR/YugMPWMrgavy31JBxGNEeM7XD2T/QTbQUSZF3NUXkgr2Qj4dF5Fs3DdzgX3EbCueHNrpuw==";
    };
    dependencies = [
      sources."jsonata-2.1.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Prettier plugin for JSONata language";
      homepage = "https://github.com/Stedi/prettier-plugin-jsonata#README.md";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  prettier-plugin-kotlin = nodeEnv.buildNodePackage {
    name = "prettier-plugin-kotlin";
    packageName = "prettier-plugin-kotlin";
    version = "2.1.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-kotlin/-/prettier-plugin-kotlin-2.1.0.tgz";
      sha512 = "DfffhPlGQqJJyUfaNJXzRlCbtQWHpFi3jzahOJ/6fxawPGnZuIWauMj9yN0daRcVLvv/pR8IXan1YkCTw5TaPw==";
    };
    dependencies = [
      sources."@korzio/djv-draft-04-2.0.1"
      sources."balanced-match-1.0.2"
      sources."brace-expansion-1.1.12"
      sources."concat-map-0.0.1"
      sources."djv-2.1.4"
      sources."fs.realpath-1.0.0"
      sources."glob-7.2.3"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."minimatch-3.1.2"
      sources."once-1.4.0"
      sources."path-is-absolute-1.0.1"
      sources."prettier-1.19.1"
      sources."wrappy-1.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "prettier plugin for the Kotlin programming language.";
      homepage = "https://github.com/Angry-Potato/prettier-plugin-kotlin#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  prettier-plugin-motoko = nodeEnv.buildNodePackage {
    name = "prettier-plugin-motoko";
    packageName = "prettier-plugin-motoko";
    version = "0.11.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-motoko/-/prettier-plugin-motoko-0.11.3.tgz";
      sha512 = "RsUqim0ZriHTxAYKHgyDBA2xu6Tp77kJFr1CfJn5vuC8OR3roCt3+4GYGVfnDCX5IqtZs8vtNp4ZUFT059xp7Q==";
    };
    dependencies = [
      sources."balanced-match-1.0.2"
      sources."brace-expansion-1.1.12"
      sources."colorette-2.0.20"
      sources."concat-map-0.0.1"
      sources."fs.realpath-1.0.0"
      sources."glob-7.2.3"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."minimatch-3.1.2"
      sources."once-1.4.0"
      sources."out-of-character-1.2.4"
      sources."path-is-absolute-1.0.1"
      sources."prettier-3.6.2"
      sources."wrappy-1.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A code formatter for the Motoko smart contract language.";
      homepage = "https://github.com/dfinity/prettier-plugin-motoko#readme";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  prettier-plugin-nginx = nodeEnv.buildNodePackage {
    name = "prettier-plugin-nginx";
    packageName = "prettier-plugin-nginx";
    version = "1.0.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-nginx/-/prettier-plugin-nginx-1.0.3.tgz";
      sha512 = "vV5q85s8XnV6NEgvz1gVLfZhmxAxY03MyOYj2ApBpjFkbs00lRsRkTmqO9L39ADuD18z1RRCcfZ3eVxKhI/nqg==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "NGINX configuration plugin for Prettier";
      homepage = "https://github.com/joedeandev/prettier-plugin-nginx";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  prettier-plugin-prisma = nodeEnv.buildNodePackage {
    name = "prettier-plugin-prisma";
    packageName = "prettier-plugin-prisma";
    version = "5.0.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-prisma/-/prettier-plugin-prisma-5.0.0.tgz";
      sha512 = "jTJV04D9+yF7ziOOMs7CJe4ijgAH7DEGjt0SAWAToGNRy1H6BEhvcKA2UQH6gC6KVW5zeeOSAvsoiDDTt9oKXg==";
    };
    dependencies = [
      sources."@prisma/prisma-schema-wasm-4.17.0-26.6b0aef69b7cdfc787f822ecd7cdc76d5f1991584"
      sources."prettier-3.6.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Prettier plugin for Prisma files";
      homepage = "https://github.com/umidbekk/prettier-plugin-prisma#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  prettier-plugin-properties = nodeEnv.buildNodePackage {
    name = "prettier-plugin-properties";
    packageName = "prettier-plugin-properties";
    version = "0.3.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-properties/-/prettier-plugin-properties-0.3.0.tgz";
      sha512 = "j2h4NbG6hIaRx0W7CDPUH+yDbzXHmI2urPC1EC8pYrsS5R5AYgAmcSDN0oea+C5mBiN6BK0AkiSKPj0RC17NDQ==";
    };
    dependencies = [
      sources."dot-properties-1.1.0"
      sources."prettier-3.6.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Prettier plugin for .properties files";
      homepage = "https://github.com/eemeli/prettier-plugin-properties#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  prettier-plugin-rust = nodeEnv.buildNodePackage {
    name = "prettier-plugin-rust";
    packageName = "prettier-plugin-rust";
    version = "0.1.9";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-rust/-/prettier-plugin-rust-0.1.9.tgz";
      sha512 = "n1DTTJQaHMdnoG/+nKUvBm3EKsMVWsYES2UPCiOPiZdBrmuAO/pX++m7L3+Hz3uuhtddpH0HRKHB2F3jbtJBOQ==";
    };
    dependencies = [
      sources."jinx-rust-0.1.6"
      sources."prettier-2.8.8"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Prettier plugin for Rust";
      homepage = "https://github.com/jinxdash/prettier-plugin-rust#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  prettier-plugin-sh = nodeEnv.buildNodePackage {
    name = "prettier-plugin-sh";
    packageName = "prettier-plugin-sh";
    version = "0.18.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-sh/-/prettier-plugin-sh-0.18.0.tgz";
      sha512 = "cW1XL27FOJQ/qGHOW6IHwdCiNWQsAgK+feA8V6+xUTaH0cD3Mh+tFAtBvEEWvuY6hTDzRV943Fzeii+qMOh7nQ==";
    };
    dependencies = [
      sources."@reteps/dockerfmt-0.3.6"
      sources."prettier-3.6.2"
      sources."sh-syntax-0.5.8"
      sources."tslib-2.8.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "An opinionated `shellscript` formatter plugin for Prettier, also support simple format of `Dockerfile`, `properties`, `gitignore`, `dotenv`, `hosts`, `jvmoptions`...";
      homepage = "https://github.com/un-ts/prettier/tree/master/packages/sh";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  prettier-plugin-solidity = nodeEnv.buildNodePackage {
    name = "prettier-plugin-solidity";
    packageName = "prettier-plugin-solidity";
    version = "2.1.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-solidity/-/prettier-plugin-solidity-2.1.0.tgz";
      sha512 = "O5HX4/PCE5aqiaEiNGbSRLbSBZQ6kLswAav5LBSewwzhT+sZlN6iAaLZlZcJzPEnIAxwLEHP03xKEg92fflT9Q==";
    };
    dependencies = [
      sources."@bytecodealliance/preview2-shim-0.17.2"
      sources."@nomicfoundation/slang-1.2.0"
      sources."@solidity-parser/parser-0.20.2"
      sources."prettier-3.6.2"
      sources."semver-7.7.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A Prettier Plugin for automatically formatting your Solidity code.";
      homepage = "https://github.com/prettier-solidity/prettier-plugin-solidity#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  prettier-plugin-sql = nodeEnv.buildNodePackage {
    name = "prettier-plugin-sql";
    packageName = "prettier-plugin-sql";
    version = "0.19.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-sql/-/prettier-plugin-sql-0.19.2.tgz";
      sha512 = "DAu1Jcanpvs32OAOXsqaVXOpPs4nFLVkB3XwzRiZZVNL5/c+XdlNxWFMiMpMhYhmCG5BW3srK8mhikCOv5tPfg==";
    };
    dependencies = [
      sources."@types/pegjs-0.10.6"
      sources."argparse-2.0.1"
      sources."big-integer-1.6.52"
      sources."commander-2.20.3"
      sources."discontinuous-range-1.0.0"
      sources."jsox-1.2.123"
      sources."moo-0.5.2"
      sources."nearley-2.20.1"
      sources."node-sql-parser-5.3.11"
      sources."prettier-3.6.2"
      sources."railroad-diagrams-1.0.0"
      sources."randexp-0.4.6"
      sources."ret-0.1.15"
      sources."sql-formatter-15.6.6"
      sources."tslib-2.8.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "An opinionated sql formatter plugin for Prettier";
      homepage = "https://github.com/un-ts/prettier/tree/master/packages/sql";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  prettier-plugin-sql-cst = nodeEnv.buildNodePackage {
    name = "prettier-plugin-sql-cst";
    packageName = "prettier-plugin-sql-cst";
    version = "0.13.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-sql-cst/-/prettier-plugin-sql-cst-0.13.0.tgz";
      sha512 = "F2NMvK/yD4BooQsNce8yyOjY5wWxJCpwaMfQEQCqkwFUmsvRsH5STGIgQILjbA1iwOsvYsJzRAEEl4hqp0aDRQ==";
    };
    dependencies = [
      sources."prettier-3.6.2"
      sources."sql-parser-cst-0.33.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Prettier plugin for SQL";
      homepage = "https://github.com/nene/prettier-plugin-sql-cst";
      license = "GPL-3.0-or-later";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  prettier-plugin-svelte = nodeEnv.buildNodePackage {
    name = "prettier-plugin-svelte";
    packageName = "prettier-plugin-svelte";
    version = "3.4.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-svelte/-/prettier-plugin-svelte-3.4.0.tgz";
      sha512 = "pn1ra/0mPObzqoIQn/vUTR3ZZI6UuZ0sHqMK5x2jMLGrs53h0sXhkVuDcrlssHwIMk7FYrMjHBPoUSyyEEDlBQ==";
    };
    dependencies = [
      sources."@jridgewell/gen-mapping-0.3.13"
      sources."@jridgewell/remapping-2.3.5"
      sources."@jridgewell/resolve-uri-3.1.2"
      sources."@jridgewell/sourcemap-codec-1.5.5"
      sources."@jridgewell/trace-mapping-0.3.30"
      sources."@sveltejs/acorn-typescript-1.0.5"
      sources."@types/estree-1.0.8"
      sources."acorn-8.15.0"
      sources."aria-query-5.3.2"
      sources."axobject-query-4.1.0"
      sources."clsx-2.1.1"
      sources."esm-env-1.2.2"
      sources."esrap-2.1.0"
      sources."is-reference-3.0.3"
      sources."locate-character-3.0.0"
      sources."magic-string-0.30.18"
      sources."prettier-3.6.2"
      sources."svelte-5.38.6"
      sources."zimmerframe-1.1.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Svelte plugin for prettier";
      homepage = "https://github.com/sveltejs/prettier-plugin-svelte#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  prettier-plugin-toml = nodeEnv.buildNodePackage {
    name = "prettier-plugin-toml";
    packageName = "prettier-plugin-toml";
    version = "2.0.6";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-toml/-/prettier-plugin-toml-2.0.6.tgz";
      sha512 = "12N/wBuHa9jd/KVy9pRP20NMKxQfQLMseQCt66lIbLaPLItvGUcSIryE1eZZMJ7loSws6Ig3M2Elc2EreNh76w==";
    };
    dependencies = [
      sources."@taplo/core-0.2.0"
      sources."@taplo/lib-0.5.0"
      sources."prettier-3.6.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "An opinionated `toml` formatter plugin for Prettier";
      homepage = "https://github.com/un-ts/prettier/tree/master/packages/toml";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
